while(True):
    x = int(input("Enter Your Number : "))
    print("")
    print("")
    print("", int(x*1)) 
    print("", int(x*2))
    print("", int(x*3))
    print("", int(x*4))
    print("", int(x*5))
    print("", int(x*6))
    print("", int(x*7))
    print("", int(x*8))
    print("", int(x*9))
    print("", int(x*10))